--Supression de toutes les tables et gestion de l'erreur SQLCODE -942
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOG_OPERATION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ECHANTILLON CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXPERIENCE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE AFFECTATION_EQUIP CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE EQUIPEMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROJET CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHERCHEUR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

--Creation des tables selon le MCD
CREATE TABLE CHERCHEUR (
    id_chercheur NUMBER PRIMARY KEY,
    nom VARCHAR2(25) NOT NULL,
    prenom VARCHAR2(25) NOT NULL,
    specialite VARCHAR2(15) NOT NULL CHECK (specialite IN ('Biotech','IA','Physique','Chimie','Mathématiques','Autre')),
    date_embauche DATE NOT NULL
);

CREATE TABLE PROJET (
    id_projet NUMBER PRIMARY KEY,
    titre VARCHAR2(100) NOT NULL,
    domaine VARCHAR2(50) NOT NULL,
    budget NUMBER NOT NULL CHECK (budget > 0),
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    id_chercheur_resp NUMBER NOT NULL,
    CONSTRAINT fk_projet_chercheur FOREIGN KEY (id_chercheur_resp) REFERENCES CHERCHEUR(id_chercheur),
    CONSTRAINT chk_dates_projet CHECK (date_fin >= date_debut)
);

CREATE TABLE EQUIPEMENT (
    id_equipement NUMBER PRIMARY KEY,
    nom VARCHAR2(50) NOT NULL,
    categorie VARCHAR2(50) NOT NULL,
    date_acquisition DATE NOT NULL,
    etat VARCHAR2(20) NOT NULL CHECK (etat IN ('Disponible','En maintenance','Hors service'))
);

CREATE TABLE AFFECTATION_EQUIP (
    id_affect NUMBER PRIMARY KEY,
    id_projet NUMBER NOT NULL,
    id_equipement NUMBER NOT NULL,
    date_affectation DATE NOT NULL,
    duree_jours NUMBER NOT NULL CHECK (duree_jours > 0),
    CONSTRAINT fk_affect_projet FOREIGN KEY (id_projet) REFERENCES PROJET(id_projet),
    CONSTRAINT fk_affect_equip FOREIGN KEY (id_equipement) REFERENCES EQUIPEMENT(id_equipement)
);

CREATE TABLE EXPERIENCE (
    id_exp NUMBER PRIMARY KEY,
    id_projet NUMBER NOT NULL,
    titre_exp VARCHAR2(100) NOT NULL,
    date_realisation DATE NOT NULL,
    resultat VARCHAR2(10),
    statut VARCHAR2(10) NOT NULL CHECK (statut IN ('En cours','Terminée','Annulée')),
    CONSTRAINT fk_exp_projet FOREIGN KEY (id_projet) REFERENCES PROJET(id_projet)
);

CREATE TABLE ECHANTILLON (
    id_echantillon NUMBER PRIMARY KEY,
    id_exp NUMBER NOT NULL,
    type_echantillon VARCHAR2(50) NOT NULL,
    date_prelevement DATE NOT NULL,
    mesure NUMBER CHECK (mesure >= 0),
    CONSTRAINT fk_echantillon_exp FOREIGN KEY (id_exp) REFERENCES EXPERIENCE(id_exp)
);

CREATE TABLE LOG_OPERATION (
    id_log NUMBER PRIMARY KEY,
    table_concernee VARCHAR2(20) NOT NULL,
    operation VARCHAR2(10) NOT NULL CHECK (operation IN ('INSERT','UPDATE','DELETE')),
    utilisateur VARCHAR2(50) NOT NULL,
    date_op DATE DEFAULT SYSDATE,
    description VARCHAR2(1000)
);
